---
dependency:
  name: galaxy
  options:
    role-file: tests/requirements.yml
driver:
  name: docker
platforms:
  - name: ansible-role-composer-1604
    image: ubuntu:16.04

lint:
  name: yamllint
  enabled: False

provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
        # Test a global requirement.
        composer_global_packages:
          - name: phpunit/phpunit
            release: "@stable"
